name: test-databases

services:
  mysql: 
    image: mysql:lts
    ports: 
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_NAME
