import { afterEach, describe, expect, it } from "vitest";
import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";

import { createProject, Dialect, DIALECTS, Project } from "./helpers";

/** An existing database with the features each DBMS uses most */
const SCHEMA: Record<Dialect, Array<string>> = {
    mysql: [
        `CREATE TABLE customers (
            id INT AUTO_INCREMENT PRIMARY KEY,
            email VARCHAR(100) NOT NULL UNIQUE,
            name VARCHAR(50) DEFAULT 'anon',
            balance DECIMAL(10,2) NOT NULL DEFAULT 0,
            created_at DATETIME(3) NOT NULL,
            born DATE,
            profile JSON,
            avatar VARBINARY(8),
            email_domain VARCHAR(100) GENERATED ALWAYS AS (SUBSTRING_INDEX(email, '@', -1)) STORED,
            manager_id INT,
            FOREIGN KEY (manager_id) REFERENCES customers (id)
        )`,
        // Name sorts before "customers", but must be created after it
        `CREATE TABLE a_orders (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            customer_id INT NOT NULL,
            total DECIMAL(10,2) NOT NULL,
            status ENUM('new', 'paid') NOT NULL DEFAULT 'new',
            CONSTRAINT fk_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE,
            INDEX idx_status (status)
        )`,
        "CREATE VIEW paid_orders AS SELECT id, total FROM a_orders WHERE status = 'paid'",
        "CREATE TRIGGER trg_orders BEFORE INSERT ON a_orders FOR EACH ROW SET NEW.total = NEW.total",
        `INSERT INTO customers (email, name, balance, created_at, born, profile, avatar, manager_id) VALUES
            ('ana@x.com', 'Ana', 10.50, '2024-01-02 03:04:05.678', '1990-05-06', '{"tags": ["a", "b"]}', X'00FF10', NULL),
            ('bob@y.com', 'O''Brien \\\\ "q"', 0, '2024-02-03 00:00:00.000', NULL, NULL, NULL, 1),
            ('eve@z.com', NULL, -3.25, '2024-03-04 05:06:07.000', '2000-01-01', '[]', X'', 2)`,
        "INSERT INTO a_orders (customer_id, total, status) VALUES (1, 99.99, 'paid'), (2, 5, 'new'), (1, 0.01, 'new')",
    ],
    postgres: [
        "CREATE TYPE mood AS ENUM ('sad', 'ok', 'happy')",
        `CREATE TABLE customers (
            id SERIAL PRIMARY KEY,
            email TEXT NOT NULL UNIQUE,
            name VARCHAR(50) DEFAULT 'anon',
            balance NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (balance > -100),
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            born DATE,
            active BOOLEAN NOT NULL DEFAULT true,
            feeling mood,
            tags TEXT[],
            profile JSONB,
            avatar BYTEA,
            email_upper TEXT GENERATED ALWAYS AS (upper(email)) STORED,
            manager_id INTEGER REFERENCES customers (id)
        )`,
        `CREATE TABLE a_orders (
            id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            customer_id INTEGER NOT NULL,
            total NUMERIC(10,2) NOT NULL,
            CONSTRAINT fk_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE
        )`,
        "CREATE TABLE notes (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, body TEXT)",
        "CREATE INDEX idx_orders_total ON a_orders (total DESC)",
        "CREATE UNIQUE INDEX idx_lower_email ON customers (lower(email))",
        "CREATE VIEW big_orders AS SELECT id, total FROM a_orders WHERE total > 10",
        "CREATE MATERIALIZED VIEW order_totals AS SELECT customer_id, sum(total) AS total FROM a_orders GROUP BY customer_id",
        "CREATE FUNCTION touch() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$",
        "CREATE TRIGGER trg_touch BEFORE UPDATE ON customers FOR EACH ROW EXECUTE FUNCTION touch()",
        `INSERT INTO customers (email, name, balance, created_at, born, active, feeling, tags, profile, avatar, manager_id) VALUES
            ('ana@x.com', 'Ana', 10.50, '2024-01-02 03:04:05.678+00', '1990-05-06', true, 'happy', '{a,"b c"}', '{"k": [1, 2]}', '\\x00ff10', NULL),
            ('bob@y.com', 'O''Brien \\ "q"', 0, '2024-02-03 00:00:00+02', NULL, false, NULL, NULL, NULL, NULL, 1),
            ('eve@z.com', NULL, -3.25, '2024-03-04 05:06:07+00', '2000-01-01', true, 'sad', '{}', '[]', '\\x', 2)`,
        "INSERT INTO a_orders (customer_id, total) VALUES (1, 99.99), (2, 5), (1, 0.01)",
        "INSERT INTO notes (id, body) VALUES (7, 'seven')",
    ],
    sqlite: [
        `CREATE TABLE customers (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            email TEXT NOT NULL UNIQUE,
            name TEXT DEFAULT 'anon',
            balance REAL NOT NULL DEFAULT 0,
            avatar BLOB,
            email_upper TEXT GENERATED ALWAYS AS (upper(email)) STORED,
            manager_id INTEGER REFERENCES customers (id)
        )`,
        `CREATE TABLE a_orders (
            id INTEGER PRIMARY KEY,
            customer_id INTEGER NOT NULL REFERENCES customers (id) ON DELETE CASCADE,
            total NUMERIC NOT NULL
        )`,
        "CREATE INDEX idx_orders_customer ON a_orders (customer_id)",
        "CREATE VIEW big_orders AS SELECT id, total FROM a_orders WHERE total > 10",
        "CREATE TRIGGER trg_orders AFTER INSERT ON a_orders BEGIN SELECT 1; END",
        `INSERT INTO customers (email, name, balance, avatar, manager_id) VALUES
            ('ana@x.com', 'Ana', 10.5, X'00FF10', NULL),
            ('bob@y.com', 'O''Brien \\ "q"', 0, NULL, 1),
            ('eve@z.com', NULL, -3.25, X'', 2)`,
        "INSERT INTO a_orders (customer_id, total) VALUES (1, 99.99), (2, 5), (1, 0.01)",
    ],
};

/** Description of the schema that must be the same in the original and the copy */
async function describeSchema(p: Project): Promise<unknown> {
    if (p.dialect === "mysql") {
        const out: Record<string, unknown> = {};
        for (const t of [...await p.tables(), "paid_orders"]) {
            const [row] = await p.query(`SHOW CREATE TABLE \`${t}\``);
            out[t] = String(row["Create Table"] ?? row["Create View"])
                .replace(/ AUTO_INCREMENT=\d+/, "")
                .replace(/ DEFINER=`[^`]*`@`[^`]*`/, "")
                .replace(/`ezm_[0-9a-f]+`\./g, "");
        }
        return out;
    }
    if (p.dialect === "postgres") {
        return {
            columns: await p.query(`
                SELECT table_name, column_name, data_type, udt_name, is_nullable, column_default,
                       is_identity, identity_generation, generation_expression
                FROM information_schema.columns WHERE table_schema = 'public' AND table_name NOT LIKE 'ez_%'
                ORDER BY table_name, ordinal_position`),
            constraints: await p.query(`
                SELECT conrelid::regclass::text AS t, conname, pg_get_constraintdef(oid) AS def FROM pg_constraint
                WHERE connamespace = 'public'::regnamespace AND conrelid::regclass::text NOT LIKE 'ez_%' ORDER BY 1, 2`),
            indexes: await p.query("SELECT indexname, indexdef FROM pg_indexes WHERE schemaname = 'public' AND tablename NOT LIKE 'ez_%' ORDER BY 1"),
            views: await p.query("SELECT c.relname, c.relkind, pg_get_viewdef(c.oid) AS def FROM pg_class c WHERE c.relkind IN ('v', 'm') AND c.relnamespace = 'public'::regnamespace ORDER BY 1"),
            types: await p.query("SELECT t.typname, e.enumlabel FROM pg_enum e JOIN pg_type t ON t.oid = e.enumtypid ORDER BY 1, e.enumsortorder"),
        };
    }
    return p.query("SELECT type, name, sql FROM sqlite_schema WHERE name NOT LIKE 'ez_%' AND type <> 'trigger' AND name NOT LIKE 'sqlite_%' ORDER BY name");
}

async function describeData(p: Project) {
    const out: Record<string, unknown> = {};
    for (const t of ["customers", "a_orders"]) out[t] = await p.query(`SELECT * FROM ${t} ORDER BY id`);
    return out;
}

function copyDir(from: string, to: string) {
    mkdirSync(to, { recursive: true });
    if (!existsSync(from)) return;
    for (const f of readdirSync(from)) copyFileSync(join(from, f), join(to, f));
}

const projects: Array<Project> = [];
function project(dialect: Dialect, trackerDialect?: Dialect) {
    const p = createProject(dialect, trackerDialect);
    projects.push(p);
    return p;
}
afterEach(async () => {
    while (projects.length) await projects.pop()!.cleanup();
});

describe.each(DIALECTS)("baseline [%s]", (dialect) => {
    it("writes the schema and data of an existing database, and an empty database built from the files is the same", async () => {
        const source = project(dialect);
        await source.setup(SCHEMA[dialect]);

        const result = source.run("baseline", "--data");
        expect(result.output).toMatch(/marked as applied/);
        expect(result.code).toBe(0);
        // Triggers and functions are not exported, and the user is told
        expect(result.output).toMatch(/Not exported[\s\S]*trg_/);

        // The source database is not changed and nothing is pending
        const migrations = readdirSync(join(source.dir, "migrations"));
        const seeds = readdirSync(join(source.dir, "seeds"));
        expect(migrations).toHaveLength(1);
        expect(migrations[0]).toMatch(/^\d{17}-baseline\.sql$/);
        expect(seeds).toHaveLength(1);
        expect(seeds[0]).toMatch(/^\d{17}-baseline-data\.sql$/);
        expect(source.run("migrate").output).toMatch(/No pending migrations/);
        expect(source.run("seed").output).toMatch(/No pending seeds/);
        const status = source.run("status").output;
        expect(status).toMatch(/✔/);
        expect(status).not.toMatch(/✘|⚠️/);

        // A new empty database built from the files
        const copy = project(dialect);
        copyDir(join(source.dir, "migrations"), join(copy.dir, "migrations"));
        copyDir(join(source.dir, "seeds"), join(copy.dir, "seeds"));
        const migrate = copy.run("migrate");
        expect(migrate.output).not.toMatch(/rror/);
        expect(migrate.code).toBe(0);
        const seed = copy.run("seed");
        expect(seed.output).not.toMatch(/rror/);
        expect(seed.code).toBe(0);

        expect(await describeSchema(copy)).toEqual(await describeSchema(source));
        expect(await describeData(copy)).toEqual(await describeData(source));

        // Auto increment ids continue after the copied rows
        await copy.query("INSERT INTO a_orders (customer_id, total) VALUES (3, 1)");
        const [last] = await copy.query("SELECT MAX(id) AS id FROM a_orders");
        expect(Number(last.id)).toBe(4);
        if (dialect === "postgres") {
            await copy.query("INSERT INTO customers (email) VALUES ('new@x.com')");
            await copy.query("INSERT INTO notes (body) VALUES ('next')");
        }

        // The down SQL removes everything
        expect(copy.run("rollback").code).toBe(0);
        expect(await copy.tables()).toEqual([]);
    });

    it("works without --data and with a custom name", async () => {
        const source = project(dialect);
        await source.setup(SCHEMA[dialect]);
        const result = source.run("baseline", "--name", "initial_schema");
        expect(result.code).toBe(0);
        expect(readdirSync(join(source.dir, "migrations"))[0]).toMatch(/-initial_schema\.sql$/);
        expect(existsSync(join(source.dir, "seeds")) ? readdirSync(join(source.dir, "seeds")) : []).toEqual([]);
        const sql = readFileSync(join(source.dir, "migrations", readdirSync(join(source.dir, "migrations"))[0]), "utf8");
        expect(sql).not.toMatch(/INSERT/i);
    });

    it("refuses when the database already uses ez-migrate", async () => {
        const source = project(dialect);
        source.addMigration("users", "CREATE TABLE users (id INTEGER PRIMARY KEY);", "DROP TABLE users;");
        expect(source.run("migrate").code).toBe(0);
        const result = source.run("baseline");
        expect(result.code).toBe(1);
        expect(result.output).toMatch(/already has applied migrations/);
        expect(readdirSync(join(source.dir, "migrations"))).toHaveLength(1);
    });

    it("refuses when the database has no tables and leaves no files", async () => {
        const source = project(dialect);
        const result = source.run("baseline", "--data");
        expect(result.code).toBe(1);
        expect(result.output).toMatch(/no tables/);
        expect(existsSync(join(source.dir, "migrations")) ? readdirSync(join(source.dir, "migrations")) : []).toEqual([]);
    });

    it("works with the tracker in another DBMS", async () => {
        const trackerDialect: Dialect = dialect === "sqlite" ? "postgres" : "sqlite";
        const source = project(dialect, trackerDialect);
        await source.setup(SCHEMA[dialect]);
        expect(source.run("baseline", "--data").code).toBe(0);
        expect(await source.tracked()).toHaveLength(1);
        expect(await source.seeded()).toHaveLength(1);
        expect(source.run("migrate").output).toMatch(/No pending migrations/);
    });
});
